package com.sunjray.osdma.SMwarehouseBModel;
// Generated Sep 12, 2019 3:09:30 PM by Hibernate Tools 4.3.5.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.sunjray.osdma.PCmodel.PcMaterialRequest;
import com.sunjray.osdma.SMmodel.QaqcProductCode;

/**
 * TOsWarhousebStockOut generated by hbm2java
 */
@Entity
@Table(name = "t_os_warhouseb_stock_out", catalog = "osdma")
public class WarhousebStockOut implements java.io.Serializable {

	private Integer whBStockOutId;
	private Date createdDate;
	private PcMaterialRequest matRequestId;
	private QaqcProductCode productCodeId;
	private Integer quantity;
	private String status;
	private String strogeLocation;

	public WarhousebStockOut() {
	}

	public WarhousebStockOut(Date createdDate, PcMaterialRequest matRequestId, QaqcProductCode productCodeId,
			Integer quantity, String status, String strogeLocation) {
		this.createdDate = createdDate;
		this.matRequestId = matRequestId;
		this.productCodeId = productCodeId;
		this.quantity = quantity;
		this.status = status;
		this.strogeLocation = strogeLocation;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "wh_b_stock_out_id", unique = true, nullable = false)
	public Integer getWhBStockOutId() {
		return this.whBStockOutId;
	}

	public void setWhBStockOutId(Integer whBStockOutId) {
		this.whBStockOutId = whBStockOutId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "mat_request_id")
	public PcMaterialRequest getMatRequestId() {
		return matRequestId;
	}

	public void setMatRequestId(PcMaterialRequest matRequestId) {
		this.matRequestId = matRequestId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "product_code_id")
	public QaqcProductCode getProductCodeId() {
		return productCodeId;
	}

	public void setProductCodeId(QaqcProductCode productCodeId) {
		this.productCodeId = productCodeId;
	}

	@Column(name = "quantity")
	public Integer getQuantity() {
		return this.quantity;
	}

	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

	@Column(name = "status", length = 10)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "stroge_location", length = 45)
	public String getStrogeLocation() {
		return this.strogeLocation;
	}

	public void setStrogeLocation(String strogeLocation) {
		this.strogeLocation = strogeLocation;
	}

}
