package com.sunjray.osdma.PCmodel;
// Generated Jul 29, 2019 8:46:52 PM by Hibernate Tools 4.3.5.Final

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * MasterTask generated by hbm2java
 */
@Entity
@Table(name = "t_os_master_task", catalog = "osdma")
public class MasterTask implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer taskId;
	private MasterWorkStage masterWorkStage;
	private String taskName;
	private Integer duration;

	public MasterTask() {
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "task_id", unique = true, nullable = false)
	public Integer getTaskId() {
		return this.taskId;
	}

	public void setTaskId(Integer taskId) {
		this.taskId = taskId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "work_stage")
	public MasterWorkStage getMasterWorkStage() {
		return this.masterWorkStage;
	}

	public void setMasterWorkStage(MasterWorkStage masterWorkStage) {
		this.masterWorkStage = masterWorkStage;
	}

	@Column(name = "task_name", length = 45)
	public String getTaskName() {
		return this.taskName;
	}

	public void setTaskName(String taskName) {
		this.taskName = taskName;
	}

	@Column(name = "duration")
	public Integer getDuration() {
		return this.duration;
	}

	public void setDuration(Integer duration) {
		this.duration = duration;
	}

}
