package com.sunjray.osdma.PMmodel;
// Generated Aug 24, 2019 2:46:59 PM by Hibernate Tools 4.3.5.Final

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.sunjray.osdma.PCmodel.MasterStationType;
import com.sunjray.osdma.PCmodel.Project;

/**
 * ProjStationMap generated by hbm2java
 */
@Entity
@Table(name = "t_os_proj_station_map", catalog = "osdma")
public class ProjStationMap implements java.io.Serializable {

	
	private static final long serialVersionUID = 1L;
	private Integer projStnMapId;
	private MasterStationType masterStationType;
	private Project project;
	private int noOfStation;

	public ProjStationMap() {
	}

	public ProjStationMap(MasterStationType masterStationType, Project project, int noOfStation) {
		this.masterStationType = masterStationType;
		this.project = project;
		this.noOfStation = noOfStation;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "proj_stn_map_id", unique = true, nullable = false)
	public Integer getProjStnMapId() {
		return this.projStnMapId;
	}

	public void setProjStnMapId(Integer projStnMapId) {
		this.projStnMapId = projStnMapId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "station_type_id", nullable = false)
	public MasterStationType getMasterStationType() {
		return this.masterStationType;
	}

	public void setMasterStationType(MasterStationType masterStationType) {
		this.masterStationType = masterStationType;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "proj_id", nullable = false)
	@JsonIgnoreProperties("pmTeamMembers")
	public Project getProject() {
		return this.project;
	}

	public void setProject(Project project) {
		this.project = project;
	}

	@Column(name = "no_of_station", nullable = false)
	public int getNoOfStation() {
		return this.noOfStation;
	}

	public void setNoOfStation(int noOfStation) {
		this.noOfStation = noOfStation;
	}

}
