package com.sunjray.osdma.PMmodel;
// Generated Aug 15, 2019 11:10:19 AM by Hibernate Tools 4.3.5.Final

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.sunjray.osdma.PCmodel.Sitecode;

/**
 * SiteLocation generated by hbm2java
 */
@Entity
@Table(name = "t_os_site_location", catalog = "osdma")
public class SiteLocation implements java.io.Serializable {
	
	private static final long serialVersionUID = 1L;
	private Integer siteLocationId;
	private Sitecode sitecode;
	private String longitude;
	private String lattitude;

	public SiteLocation() {
	}

	public SiteLocation(Sitecode sitecode, String longitude, String lattitude) {
		this.sitecode = sitecode;
		this.longitude = longitude;
		this.lattitude = lattitude;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "site_location_id", unique = true, nullable = false)
	public Integer getSiteLocationId() {
		return this.siteLocationId;
	}

	public void setSiteLocationId(Integer siteLocationId) {
		this.siteLocationId = siteLocationId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JsonIgnoreProperties("siteLocation")
	@JoinColumn(name = "sitecode_id")
	public Sitecode getSitecode() {
		return this.sitecode;
	}

	public void setSitecode(Sitecode sitecode) {
		this.sitecode = sitecode;
	}

	@Column(name = "longitude", length = 45)
	public String getLongitude() {
		return this.longitude;
	}

	public void setLongitude(String longitude) {
		this.longitude = longitude;
	}

	@Column(name = "lattitude", length = 45)
	public String getLattitude() {
		return this.lattitude;
	}

	public void setLattitude(String lattitude) {
		this.lattitude = lattitude;
	}

}
