package com.sunjray.osdma.SMmodel;

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.sunjray.osdma.PCmodel.MasterComponent;
import com.sunjray.osdma.PCmodel.MasterProduct;

/**
 * QaqcMaterialCode generated by Smruti
 */
@Entity
@Table(name = "t_os_qaqc_material_code", catalog = "osdma")
public class QaqcMaterialCode implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private Integer materialCodeId;
	private MasterComponent masterComponent;
	private MasterProduct masterProduct;
	private QaqcItems qaqcItems;
	private Date createdDate;
	private String simProvider;
	private Integer phoneNo;
	private String imeiNo;


	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "material_code_id", unique = true, nullable = false)
	public Integer getMaterialCodeId() {
		return this.materialCodeId;
	}

	public void setMaterialCodeId(Integer materialCodeId) {
		this.materialCodeId = materialCodeId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "component_id")
	public MasterComponent getMasterComponent() {
		return this.masterComponent;
	}

	public void setMasterComponent(MasterComponent masterComponent) {
		this.masterComponent = masterComponent;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "product_id")
	public MasterProduct getMasterProduct() {
		return this.masterProduct;
	}

	public void setMasterProduct(MasterProduct masterProduct) {
		this.masterProduct = masterProduct;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "item_id")
	public QaqcItems getQaqcItems() {
		return this.qaqcItems;
	}

	public void setQaqcItems(QaqcItems qaqcItems) {
		this.qaqcItems = qaqcItems;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "sim_provider", length = 45)
	public String getSimProvider() {
		return this.simProvider;
	}

	public void setSimProvider(String simProvider) {
		this.simProvider = simProvider;
	}

	@Column(name = "phone_no")
	public Integer getPhoneNo() {
		return this.phoneNo;
	}

	public void setPhoneNo(Integer phoneNo) {
		this.phoneNo = phoneNo;
	}

	@Column(name = "imei_no", length = 45)
	public String getImeiNo() {
		return this.imeiNo;
	}

	public void setImeiNo(String imeiNo) {
		this.imeiNo = imeiNo;
	}

}
